sudo: required

services:
      - docker

before_install:
      - docker build -t himanshumonga32/docker-react -f Dockerfile.dev .

script:
      - docker run himanshumonga32/docker-react npm run test -- --coverage
